on: 
  push:
    paths:
    - '.github/workflows/**'
    # Runs at every pull requests submitted in master branch 
    branches: [ master ]
  schedule:
    - cron:  '* */2 * * *'
name: Sync with Gitee
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Mirror Github to Gitee
      uses: Yikun/hub-mirror-action@v0.09
      with:
        src: gitee/totalcontrol
        dst: github/maniaciachao
        dst_key: ${{ secrets.API_PRIVATE_KEY }}
        dst_token: ${{ secrets.API_TOKEN }}
        account_type: user
        static_list: 'hustzc'
        force_update: true
        # debug: true